version: '3'

services:
  development:
    build:
      context: .
      target: development
    ports:
      - "300:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app

  dependencies:
    build:
      context: .
      target: dependencies
    environment:
      NODE_ENV: production

  builder:
    build:
      context: .
      target: builder
    environment:
      NODE_ENV: development
    volumes:
      - .:/app

  production:
    build:
      context: .
      target: production
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    user: node

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - production
